import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#EAEAEA',
    width: 320,
    overflow: 'hidden',
    position: 'relative',
    paddingBottom: 70,
    borderRadius: 8,
  },
  outOfStockContainer: {
    opacity: 0.65,
  },
  outOfStockBadge: {
    position: 'absolute',
    top: 12,
    right: 0,
    backgroundColor: '#E74C3C',
    paddingHorizontal: 12,
    paddingVertical: 5,
    zIndex: 10,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  outOfStockText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  stockBadge: {
    position: 'absolute',
    top: 12,
    right: 0,
    backgroundColor: '#27AE60',
    paddingHorizontal: 10,
    paddingVertical: 4,
    zIndex: 10,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  stockBadgeText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 11,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    paddingLeft: 15,
    paddingRight: 90,
    paddingVertical: 12,
  },
  name: {
    fontSize: 20,
    fontWeight: '900',
    color: '#000',
    flex: 1,
  },
  type: {
    fontSize: 13,
    color: '#555',
    fontWeight: '400',
    marginLeft: 8,
  },
  imageContainer: {
    height: 190,
    width: '100%',
    backgroundColor: '#d9d9d9',
  },
  image: {
    width: 320,
    height: 190,
  },
  imagePlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#c9d6c3',
  },
  imagePlaceholderText: {
    fontSize: 60,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginTop: 12,
  },
  leftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stars: {
    flexDirection: 'row',
    gap: 1,
  },
  starIcon: {
    fontSize: 12,
  },
  scoreBadge: {
    backgroundColor: '#FDE17A',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 14,
  },
  scoreText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111',
  },
  price: {
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 14,
    marginBottom: 8,
    color: '#000',
  },
  buttonContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 60,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  pressableButtonWrapper: {
    width: '100%',
    height: '100%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#5A7D71',
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  buttonDisabled: {
    backgroundColor: '#999',
  },
  buttonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  buttonTextDisabled: {
    color: '#ddd',
  },
});